// Reviewed individually for short, concrete, everyday meanings; no template fallback.
const groups = {
vehiculos:[
['El coche es rojo.','小汽车是红色的。'],['El autobús es grande.','公交车很大。'],['El camión lleva cajas.','卡车运箱子。'],['El tren va por la vía.','火车沿着轨道行驶。'],['Voy en bicicleta.','我骑自行车。'],['La moto tiene dos ruedas.','摩托车有两个轮子。'],['El avión vuela.','飞机在飞。'],['El barco va por el mar.','轮船在海上航行。'],['El helicóptero vuela.','直升机在飞。'],['Viene una ambulancia.','一辆救护车来了。'],['El camión de bomberos tiene una escalera.','消防车有梯子。'],['Viene un coche de policía.','一辆警车来了。'],['Vamos en taxi.','我们坐出租车吧。'],['El tractor va despacio.','拖拉机慢慢地开。'],['El cohete sube.','火箭升起来了。'],['Voy en patinete.','我滑滑板车。'],['Vamos en furgoneta.','我们坐面包车。'],['El velero tiene una vela.','帆船有一面帆。'],['La canoa va por el río.','独木舟在河上划行。'],['El teleférico sube.','缆车升上去了。']],
animales:[
['El perro corre.','小狗在跑。'],['El gato duerme.','小猫在睡觉。'],['El conejo salta.','兔子在跳。'],['El oso es grande.','熊很大。'],['El panda come.','熊猫在吃东西。'],['El león ruge.','狮子在吼叫。'],['El tigre tiene rayas.','老虎有条纹。'],['La vaca da leche.','奶牛产牛奶。'],['El cerdo come.','小猪在吃东西。'],['El caballo corre.','马在跑。'],['La oveja tiene lana.','绵羊有羊毛。'],['El mono sube al árbol.','猴子爬上树。'],['El elefante tiene trompa.','大象有长鼻子。'],['La jirafa es alta.','长颈鹿很高。'],['El pato nada.','鸭子在游泳。'],['El pollo es pequeño.','小鸡很小。'],['El pez nada.','鱼在游泳。'],['La tortuga va despacio.','乌龟慢慢走。'],['La mariposa vuela.','蝴蝶在飞。'],['La abeja vuela.','蜜蜂在飞。']],
comida:[
['Quiero pan.','我想吃面包。'],['Quiero leche.','我想喝牛奶。'],['Quiero un huevo.','我想吃一个鸡蛋。'],['Me gusta el queso.','我喜欢奶酪。'],['Quiero arroz.','我想吃米饭。'],['Me gusta la pasta.','我喜欢意大利面。'],['La sopa está caliente.','汤是热的。'],['Compartimos la pizza.','我们一起分享披萨。'],['El helado está frío.','冰淇淋是凉的。'],['Quiero una galleta.','我想吃一块饼干。'],['La tarta es para compartir.','蛋糕是大家一起分享的。'],['Quiero agua.','我想喝水。'],['La zanahoria es naranja.','胡萝卜是橙色的。'],['Quiero una patata.','我想吃一个土豆。'],['El maíz es amarillo.','玉米是黄色的。'],['El tomate es rojo.','番茄是红色的。'],['El brócoli es verde.','西兰花是绿色的。'],['El pepino es verde.','黄瓜是绿色的。'],['Quiero un poco de carne.','我想吃一点肉。'],['Hoy comemos pescado.','今天我们吃鱼。']],
frutas:[
['Quiero una manzana.','我想吃一个苹果。'],['La pera es verde.','梨是绿色的。'],['Pela el plátano.','剥开香蕉。'],['La naranja tiene zumo.','橙子有果汁。'],['El limón es amarillo.','柠檬是黄色的。'],['La fresa es roja.','草莓是红色的。'],['Me gustan las uvas.','我喜欢葡萄。'],['La sandía es grande.','西瓜很大。'],['Compartimos el melón.','我们一起分享甜瓜。'],['El melocotón es suave.','桃子摸起来软软的。'],['La cereza es pequeña.','樱桃很小。'],['La piña tiene hojas.','菠萝有叶子。'],['El kiwi es verde por dentro.','猕猴桃里面是绿色的。'],['El mango es dulce.','芒果是甜的。'],['El coco tiene una cáscara dura.','椰子有硬壳。'],['El arándano es pequeño.','蓝莓很小。']],
cuerpo:[
['Dame la mano.','把手给我。'],['Este es mi pie.','这是我的脚。'],['Cierra un ojo.','闭上一只眼睛。'],['Esta es mi oreja.','这是我的耳朵。'],['Toca tu nariz.','摸摸你的鼻子。'],['Abre la boca.','张开嘴。'],['Saca la lengua.','伸出舌头。'],['Este es mi diente.','这是我的牙齿。'],['Mueve la cabeza.','动动脑袋。'],['Levanta el brazo.','举起手臂。'],['Dobla la pierna.','弯弯腿。'],['Mi corazón late.','我的心在跳。'],['Levanta el pulgar.','竖起拇指。'],['Este es mi dedo.','这是我的手指。'],['Me peino el pelo.','我梳头发。']],
casa:[
['Vamos a casa.','我们回家吧。'],['Abre la puerta.','打开门。'],['Cierra la ventana.','关上窗户。'],['Voy a la cama.','我要上床了。'],['Me siento en el sofá.','我坐在沙发上。'],['Siéntate en la silla.','坐到椅子上。'],['Enciende la lámpara.','打开灯。'],['Me baño en la bañera.','我在浴缸里洗澡。'],['Me doy una ducha.','我淋浴。'],['Quiero hacer pis.','我想尿尿。'],['Me veo en el espejo.','我在镜子里看见自己。'],['Barremos con la escoba.','我们用扫帚扫地。'],['Me lavo con jabón.','我用肥皂洗。'],['Pon los juguetes en la cesta.','把玩具放进篮子。'],['Aquí está la llave.','钥匙在这里。'],['El reloj hace tic-tac.','时钟滴答滴答响。'],['Apagamos la televisión.','我们关掉电视。'],['El teléfono suena.','电话响了。'],['Como con la cuchara.','我用勺子吃东西。'],['Este es mi plato.','这是我的盘子。']],
ropa:[
['Quiero esta camiseta.','我想穿这件上衣。'],['Me pongo el pantalón.','我穿上裤子。'],['Me gusta este vestido.','我喜欢这条裙子。'],['Ponte el abrigo.','穿上外套。'],['Me pongo los calcetines.','我穿上袜子。'],['Ponte los zapatos.','穿上鞋子。'],['Mis botas son grandes.','我的靴子很大。'],['Me pongo la gorra.','我戴上鸭舌帽。'],['Este es mi sombrero.','这是我的帽子。'],['La bufanda me abriga.','围巾让我暖和。'],['Me pongo los guantes.','我戴上手套。'],['Coge tu mochila.','拿上你的背包。'],['Estas son mis gafas.','这是我的眼镜。'],['Me pongo el bañador.','我穿上泳衣。'],['Me pongo el pijama.','我穿上睡衣。'],['Me pongo las sandalias.','我穿上凉鞋。']],
personas:[
['Mamá, ven.','妈妈，过来。'],['Papá, ayúdame.','爸爸，帮帮我。'],['El bebé duerme.','宝宝在睡觉。'],['La niña juega.','女孩在玩。'],['El niño salta.','男孩在跳。'],['Hola, abuela.','奶奶／外婆，你好。'],['Hola, abuelo.','爷爷／外公，你好。'],['Esta es mi familia.','这是我的家人。'],['Juego con mi hermana.','我和姐妹一起玩。'],['Juego con mi hermano.','我和兄弟一起玩。'],['Esta es mi amiga.','这是我的朋友。'],['Este es mi amigo.','这是我的朋友。'],['La médica me ayuda.','女医生帮助我。'],['El bombero apaga el fuego.','消防员灭火。'],['El policía nos ayuda.','警察帮助我们。'],['La profesora lee un cuento.','女老师在读故事。']],
naturaleza:[
['El sol brilla.','太阳闪闪发光。'],['La luna está en el cielo.','月亮在天上。'],['La estrella brilla.','星星闪闪发光。'],['La nube es blanca.','云是白色的。'],['Está lloviendo.','正在下雨。'],['La nieve es blanca.','雪是白色的。'],['El arcoíris tiene muchos colores.','彩虹有很多颜色。'],['El árbol es alto.','树很高。'],['La flor es rosa.','花是粉色的。'],['La hoja es verde.','叶子是绿色的。'],['La montaña es alta.','山很高。'],['El mar tiene olas.','海上有浪。'],['El fuego está caliente.','火是热的。'],['La piedra es dura.','石头是硬的。'],['Tengo una concha.','我有一个贝壳。'],['El bosque tiene árboles.','森林里有树。'],['El volcán es una montaña.','火山是一座山。'],['La Tierra es nuestro planeta.','地球是我们的星球。']]
};
export function everydaySentence(category,index){return groups[category]?.[index];}
